### ISSUE TITLE
No module named 'eyediagram._brescount'

### ISSUE THREAD

**Issue by ybxbupt** [WarrenWeckesser/eyediagram#7]
when I run mpl_demo.py, error occured:
Traceback (most recent call last):
  File "I:/guojianxin/eyediagram-master/demo/bok_demo.py", line 5, in <module>
    from eyediagram.bok import eyediagram
  File "I:\guojianxin\eyediagram-master\eyediagram\bok.py", line 8, in <module>
    from .core import grid_count as _grid_count
  File "I:\guojianxin\eyediagram-master\eyediagram\core.py", line 8, in <module>
    from ._brescount import bres_curve_count as _bres_curve_count
ModuleNotFoundError: No module named 'eyediagram._brescount'

**Comment by WarrenWeckesser** [comment]
This is an old issue that was probably the result of not installing `eyediagram` correctly.  I'm closing it as it is probably no longer of interest. (I had stopped developing eyediagram for quite a few years, and didn't have time for support.)
